import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavBar from "../../components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <meta name="google-site-verification" content="EokArCp9yyGbD2BmcxchD4K-aipg9a64Y_e0D8syu44" />
      </head>
      <body className={inter.className}>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
