import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavBar from "../../components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <meta name="google-site-verification" content="EokArCp9yyGbD2BmcxchD4K-aipg9a64Y_e0D8syu44" />
      </head>
      <body className={inter.className}>
        <NavBar/>
        <ul className="bg-black text-white flex gap-6 p-2">
          <Link href="/" className=" hover:bg-slate-800 p-2 rounded">Home</Link>
          <br/>
          <Link href="/products" className=" hover:bg-slate-800 p-2 rounded">Produtos</Link>
          <br/>
          <Link href="/about" className=" hover:bg-slate-800 p-2 rounded">Sobre nós</Link>
        </ul>
        {children}
      </body>
    </html>
  );
}
